#pragma once

#include <QJsonObject>
#include <QString>

namespace caelestia::config {

inline QJsonObject defaultKeybinds() {
    return QJsonObject{ { QStringLiteral("nexus"), QStringLiteral("") },
        { QStringLiteral("showall"), QStringLiteral("") }, { QStringLiteral("dashboard"), QStringLiteral("") },
        { QStringLiteral("screenshot"), QStringLiteral("Meta+Shift+S") },
        { QStringLiteral("overview"), QStringLiteral("Meta+Tab") },
        { QStringLiteral("googleLens"), QStringLiteral("Meta+Shift+A") },
        { QStringLiteral("ocr"), QStringLiteral("Meta+Shift+D") },
        { QStringLiteral("screenRecording"), QStringLiteral("Meta+Ctrl+S") },
        { QStringLiteral("lock"), QStringLiteral("Meta+L") },
        { QStringLiteral("session"), QStringLiteral("Ctrl+Alt+Delete") },
        { QStringLiteral("launcher"), QStringLiteral("Meta+Space; Meta") },
        { QStringLiteral("launcherInterrupt"), QStringLiteral("") },
        { QStringLiteral("sidebar"), QStringLiteral("Meta+B") }, { QStringLiteral("aiAssistant"), QStringLiteral("") },
        { QStringLiteral("utilities"), QStringLiteral("") },
        { QStringLiteral("emoji"), QStringLiteral("Meta+Shift+V") },
        { QStringLiteral("clipboard"), QStringLiteral("Meta+V") },
        { QStringLiteral("windowSwitcher"), QStringLiteral("Alt+Tab") },
        { QStringLiteral("windowSwitcherReverse"), QStringLiteral("Alt+Shift+Tab") },
        { QStringLiteral("wallpaper"), QStringLiteral("Meta+Ctrl+T") },
        { QStringLiteral("keybinds"), QStringLiteral("Meta+/") }, { QStringLiteral("whatsnew"), QStringLiteral("") },
        { QStringLiteral("foot"), QStringLiteral("Meta+Return") },
        { QStringLiteral("firefox"), QStringLiteral("Meta+W") }, { QStringLiteral("code"), QStringLiteral("Meta+C") },
        { QStringLiteral("github-desktop"), QStringLiteral("Meta+G") },
        { QStringLiteral("nemo"), QStringLiteral("Meta+Alt+E") },
        { QStringLiteral("kcolorpicker"), QStringLiteral("Meta+Shift+C") },
        { QStringLiteral("krohnkiteFocusUp"), QStringLiteral("Meta+Up") },
        { QStringLiteral("krohnkiteFocusDown"), QStringLiteral("Meta+Down") },
        { QStringLiteral("krohnkiteFocusLeft"), QStringLiteral("Meta+Left") },
        { QStringLiteral("krohnkiteFocusRight"), QStringLiteral("Meta+Right") },
        { QStringLiteral("krohnkiteShiftUp"), QStringLiteral("Meta+Shift+Up") },
        { QStringLiteral("krohnkiteShiftDown"), QStringLiteral("Meta+Shift+Down") },
        { QStringLiteral("krohnkiteShiftLeft"), QStringLiteral("Meta+Shift+Left") },
        { QStringLiteral("krohnkiteShiftRight"), QStringLiteral("Meta+Shift+Right") },
        { QStringLiteral("krohnkiteCloseWindow"), QStringLiteral("Meta+Q") },
        { QStringLiteral("krohnkiteFocusNext"), QStringLiteral("") },
        { QStringLiteral("krohnkiteFocusPrev"), QStringLiteral("") },
        { QStringLiteral("krohnkiteSetMaster"), QStringLiteral("") },
        { QStringLiteral("krohnkiteNextLayout"), QStringLiteral("") },
        { QStringLiteral("krohnkitePreviousLayout"), QStringLiteral("") },
        { QStringLiteral("krohnkiteBTreeLayout"), QStringLiteral("") },
        { QStringLiteral("krohnkiteMonocleLayout"), QStringLiteral("") },
        { QStringLiteral("krohnkiteFloatingLayout"), QStringLiteral("") },
        { QStringLiteral("krohnkiteQuarterLayout"), QStringLiteral("") },
        { QStringLiteral("krohnkiteSpreadLayout"), QStringLiteral("") },
        { QStringLiteral("krohnkiteStackedLayout"), QStringLiteral("") },
        { QStringLiteral("krohnkiteStairLayout"), QStringLiteral("") },
        { QStringLiteral("krohnkiteColumnsLayout"), QStringLiteral("") },
        { QStringLiteral("krohnkiteThreeColumnLayout"), QStringLiteral("") },
        { QStringLiteral("krohnkiteSpiralLayout"), QStringLiteral("") },
        { QStringLiteral("krohnkiteTileLayout"), QStringLiteral("") },
        { QStringLiteral("krohnkiteGrowHeight"), QStringLiteral("") },
        { QStringLiteral("krohnkiteShrinkHeight"), QStringLiteral("") },
        { QStringLiteral("krohnkiteGrowWidth"), QStringLiteral("") },
        { QStringLiteral("krohnkiteShrinkWidth"), QStringLiteral("") },
        { QStringLiteral("krohnkiteIncreaseMaster"), QStringLiteral("") },
        { QStringLiteral("krohnkiteDecreaseMaster"), QStringLiteral("") },
        { QStringLiteral("krohnkiteToggleFloat"), QStringLiteral("") },
        { QStringLiteral("krohnkiteFloatAll"), QStringLiteral("") },
        { QStringLiteral("krohnkiteRotate"), QStringLiteral("") },
        { QStringLiteral("krohnkiteRotatePart"), QStringLiteral("") },
        { QStringLiteral("krohnkiteToggleDock"), QStringLiteral("") },
        { QStringLiteral("screenshotFreeze"), QStringLiteral("") },
        { QStringLiteral("screenshotClip"), QStringLiteral("") },
        { QStringLiteral("screenshotFreezeClip"), QStringLiteral("") },
        { QStringLiteral("unlock"), QStringLiteral("") }, { QStringLiteral("regionScreenshot"), QStringLiteral("") },
        { QStringLiteral("regionSearch"), QStringLiteral("") }, { QStringLiteral("regionOcr"), QStringLiteral("") },
        { QStringLiteral("regionRecord"), QStringLiteral("") },
        { QStringLiteral("regionRecordWithSound"), QStringLiteral("") },
        { QStringLiteral("brightnessUp"), QStringLiteral("") },
        { QStringLiteral("brightnessDown"), QStringLiteral("") },
        { QStringLiteral("refreshDevices"), QStringLiteral("") }, { QStringLiteral("mediaToggle"), QStringLiteral("") },
        { QStringLiteral("mediaPrev"), QStringLiteral("") }, { QStringLiteral("mediaNext"), QStringLiteral("") },
        { QStringLiteral("mediaStop"), QStringLiteral("") }, { QStringLiteral("clearNotifs"), QStringLiteral("") },
        { QStringLiteral("workspace1"), QStringLiteral("Meta+1") },
        { QStringLiteral("workspace2"), QStringLiteral("Meta+2") },
        { QStringLiteral("workspace3"), QStringLiteral("Meta+3") },
        { QStringLiteral("workspace4"), QStringLiteral("Meta+4") },
        { QStringLiteral("workspace5"), QStringLiteral("Meta+5") },
        { QStringLiteral("workspace6"), QStringLiteral("Meta+6") },
        { QStringLiteral("workspace7"), QStringLiteral("Meta+7") },
        { QStringLiteral("workspace8"), QStringLiteral("Meta+8") },
        { QStringLiteral("workspace9"), QStringLiteral("Meta+9") },
        { QStringLiteral("workspace10"), QStringLiteral("Meta+0") } };
}

} // namespace caelestia::config
